export const NAVBAR_UPDATE = "NAVBAR_UPDATE";
export const SIDENAV_UPDATE = "SIDENAV_UPDATE";
export const SEARCH_HOTKEY = "SEARCH_HOTKEY";
export const SEARCH_QUERY = "SEARCH_QUERY";

//AUTH
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const SETUSER = "SETUSER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const PUBLISH = "PUBLISH";
// export const ENABLE_USER = "ENABLE_USER";
// export const DISABLE_USER = "DISABLE_USER";

//POSTS
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const SELECT_POST = "SELECT_POST";
export const GET_POSTS_BY_USER_ID = "GET_POSTS_BY_USER_ID";
export const GET_VOLUNTEERED_POSTS = "GET_VOLUNTEERED_POSTS";
export const DELETE_POST_BY_ID = "DELETE_POST_BY_ID";
export const ADD_POST_SKILL = "ADD_POST_SKILL";
export const EDIT_POST_BY_ID = "EDIT_POST_BY_ID";

//COMMENT
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const GET_COMMENTS_BY_POST_ID = "GET_COMMENTS_BY_POST_ID";
export const DELETE_COMMENT_BY_ID = "DELETE_COMMENT_BY_ID";
export const ADD_REPLY = "ADD_REPLY";

//VOLUNTEER
export const ADD_VOLUNTEER = "ADD_VOLUNTEER";
export const GET_ALL_VOLUNTEERS = "GET_ALL_VOLUNTEERS";
export const GET_VOLUNTEERS_BY_USER_ID = "GET_VOLUNTEERS_BY_USER_ID";

//USERS
export const GETUSER = "GETUSER";
export const GET_DISABLED_USERS = "GET_DISABLED_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";
export const ADD_USER_SKILL = "ADD_USER_SKILL";
export const VERIFY_USER = "VERIFY_USER";
export const UNVERIFY_USER = "UNVERIFY_USER";
export const ENABLE_USER = "ENABLE_USER";
export const DISABLE_USER = "DISABLE_USER";



//SKILLS
export const ADD_SKILL = "ADD_SKILL";
export const GET_ALL_SKILLS = "GET_ALL_SKILLS";

//REPORT POST
export const REPORT_POST = "REPORT_POST";
export const GET_ALL_REPORTED_POSTS = "GET_ALL_REPORTED_POSTS";
export const GET_REPORTED_POSTS_BY_USER_ID = "GET_REPORTED_POSTS_BY_USER_ID";
export const CLEAR_POST_REPORTS = "CLEAR_POST_REPORTS";
export const DELETE_REPORTED_POST = "DELETE_REPORTED_POST";

//REPORT USER
export const REPORT_USER = "REPORT_USER";
export const GET_ALL_REPORTED_USERS = "GET_ALL_REPORTED_USERS";
export const GET_REPORTED_USERS_BY_USER_ID = "GET_REPORTED_USERS_BY_USER_ID";
export const CLEAR_USER_REPORTS = "CLEAR_USER_REPORTS";
